---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: otus-msa-hw5
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: auth-service
