apiVersion: apps/v1
kind: StatefulSet

metadata:
  name: postgresql-db-profile

spec:
  serviceName: db-service-profile
  selector:
    matchLabels:
      app: postgresql-db-profile
  replicas: 1
  template:
    metadata:
      labels:
        app: postgresql-db-profile
    spec:
      containers:
        - name: postgresql-db-profile
          image: postgres:14.4
          volumeMounts:
          - name: postgresql-db-disk
            mountPath: /data
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: example
            - name: POSTGRES_DB
              value: postgres
            - name: PGDATA
              value: /data/pgdata
  volumeClaimTemplates:
  - metadata:
      name: postgresql-db-disk
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 1Gi
